### ISSUE TITLE
Radial distance utility lightly broken by CadQuery magnets PR

### ISSUE THREAD

**Issue by connoramoreno** [svalinn/parastell#149]
As foreseen by @Edgar-21, the radial distance utility does not work with the newest version of the magnet routine. I imagine and am hopeful that adapting `radial_distance_utils.py` and `radial_build_distance_example.py` won't be too difficult.

**Comment by Edgar-21** [comment]
If you want to have at it, I likely won't get to it until later this week. If I recall correctly the main issue is some member variables changed names and maybe some methods got moved around? The problems should be localized to this function https://github.com/svalinn/parastell/blob/d768c7281a610c81d87bc5ae523cad62585c7212/parastell/radial_distance_utils.py#L104 Let me know if you start otherwise I'll get to it eventually
